highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://zhoujli.github.io/resume
author: Zhou (Joe) Li

baseurl: /resume/
title: Zhou (Joe) Li's Resume
name: Zhou (Joe) Li
email: zli15@ncsu.edu
email_full: mailto:zli15@ncsu.edu
website: zhoujli.github.io
website_full: http://zhoujli.github.io
linkedin: in/zhouli89
github: zhoujli
tel: +1 (919) 599-3667
tel_full: tel:+19195993667
google_maps: 'https://www.google.com/maps/place/NC+State+Department+of+Statistics/@35.7848033,-78.668946,17z/data=!3m1!4b1!4m2!3m1!1s0x89acf58e6c84853b:0xbf4f4c3ad2c4f9c1'
address: 2311 Stinson Dr
postcode: 27695
city: Raleigh
country: United States
google_analytics: UA-73356853-1
