highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://cgte88586.github.io/resume
author: Zhou (Joe) Li

baseurl: /resume/
title: Zhou (Joe) Li's Resume
name: Zhou (Joe) Li
email: zli15@ncsu.edu
email_full: mailto:zli15@ncsu.edu
website: cgte88586.github.io
website_full: http://cgte88586.github.io
github: cgte88586
twitter: ZhouLi9
tel: +1 (919) 599-3667
tel_full: tel:+19195993667
google_maps: 'https://www.google.com/maps/place/Raleigh,+NC/@35.8436867,-78.7851381,11z/data=!3m1!4b1!4m2!3m1!1s0x89ac5a2f9f51e0f7:0x6790b6528a11f0ad'
address: 3000 Gregory Manor Ct
postcode: 27518
city: Cary
country: United States
google_analytics: UA-73356853-1
